{{- if .Values.cachetMonitor.cachetToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachet-url-monitor.fullname" . }}
type: Opaque
data:
  token: {{ .Values.cachetMonitor.cachetToken | b64enc | quote }}
{{- end }}
